function xdot = f_arm_dynamics(t, x, params)
% Benjamin Hsu
% ME500 Final Project
%
% SCRIPT: f_arm_dynamics.m
% PURPOSE: Calculates the differential equations of motion for the 3-DOF Arm.
% This function is called by ode45 to simulate the robot's motion.
%
% INPUTS:
%   t      : Current time (seconds)
%   x      : State vector [q1; q2; q3; dq1; dq2; dq3]
%   params : Structure containing all physical constants (mass, length, inertia)
%
% OUTPUT:
%   xdot   : Time derivative of state [dq1; dq2; dq3; ddq1; ddq2; ddq3]

    %% Extract State Vector

    % Positions (angles)
    q1 = x(1);
    q2 = x(2);
    q3 = x(3);

    % Velocities (Angular rates)
    dq1 = x(4);
    dq2 = x(5);
    dq3 = x(6);

    %% Extract Physical Constants

    % Mass and length of links
    a2 = params.a2;
    a3 = params.a3;
    m1 = params.m1;
    m2 = params.m2;
    m3 = params.m3;
    g = params.g;

    % Inertias
    Ixx1 = params.I1(1,1); Iyy1 = params.I1(2,2); Izz1 = params.I1(3,3);
    Ixx2 = params.I2(1,1); Iyy2 = params.I2(2,2); Izz2 = params.I2(3,3);
    Ixx3 = params.I3(1,1); Iyy3 = params.I3(2,2); Izz3 = params.I3(3,3);

    %% Calculate Dynamics
    % Call autogenerated files from derive_arm_equations.m
    B = get_B_matrix(q1, q2, q3, m1, m2, m3, a2, a3, Ixx1, Iyy1, Izz1, Ixx2, Iyy2, Izz2, Ixx3, Iyy3, Izz3);
    C = get_C_matrix(q1, q2, q3, dq1, dq2, dq3, m1, m2, m3, a2, a3, Ixx1, Iyy1, Izz1, Ixx2, Iyy2, Izz2, Ixx3, Iyy3, Izz3);
    G = get_G_vector(q1, q2, q3, m1, m2, m3, a2, a3, g);

    %% Control
    % 1. Generate Trajectory (Position, Velocity, AND Acceleration)
    [q_des, dq_des, ddq_des] = get_cubic_traj(t, params.traj_start_time, ...
                                              params.traj_duration, ...
                                              params.q_start, ...
                                              params.q_target);

    % 2. Organize current state
    q_curr  = [q1; q2; q3];
    dq_curr = [dq1; dq2; dq3];

    % 3. Call Computed Torque Controller
    % We pass B, C, G so the controller can "cancel" them out
    tau = get_control_torque(q_curr, dq_curr, q_des, dq_des, ddq_des, ...
                             B, C, G, params);

    %% Friction
    damping_coeff = 0.5;
    tau = tau - damping_coeff * [dq1; dq2; dq3];

    %% Compute Acceleration
    % Equation of Motion: B * q_dd + C * q_d + G = tau
    % Solving for q_dd:   q_dd = inv(B) * (tau - C*q_d - G)

    velocity_vector = [dq1; dq2; dq3];
    q_dd = B \ (tau - C * velocity_vector - G);
    xdot = [velocity_vector; q_dd];

end