function G_vect = get_G_vector(q1,q2,q3,m1,m2,m3,a2,a3,g)
%get_G_vector
%    G_vect = get_G_vector(Q1,Q2,Q3,M1,M2,M3,A2,A3,G)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    04-Dec-2025 21:38:58

t2 = cos(q2);
t3 = q2+q3;
t4 = cos(t3);
G_vect = [0.0;g.*m3.*(a2.*t2+(a3.*t4)./2.0)+(a2.*g.*m2.*t2)./2.0;(a3.*g.*m3.*t4)./2.0];
end
