function C_mat = get_C_matrix(q1,q2,q3,dq1,dq2,dq3,m1,m2,m3,a2,a3,Ixx1,Iyy1,Izz1,Ixx2,Iyy2,Izz2,Ixx3,Iyy3,Izz3)
%get_C_matrix
%    C_mat = get_C_matrix(Q1,Q2,Q3,DQ1,DQ2,DQ3,M1,M2,M3,A2,A3,Ixx1,Iyy1,Izz1,Ixx2,Iyy2,Izz2,Ixx3,Iyy3,Izz3)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    07-Dec-2025 02:38:17

t2 = sin(q3);
t3 = a2.^2;
t4 = a3.^2;
t5 = q2.*2.0;
t6 = q3.*2.0;
t7 = sin(t5);
t8 = q3+t5;
t10 = t5+t6;
t12 = (a2.*a3.*m3.*t2)./4.0;
t15 = (a2.*a3.*dq2.*m3.*t2)./2.0;
t9 = sin(t8);
t11 = sin(t10);
t13 = (Ixx2.*t7)./2.0;
t14 = (Iyy2.*t7)./2.0;
t17 = -t15;
t18 = (m3.*t3.*t7)./2.0;
t23 = (m2.*t3.*t7)./8.0;
t16 = -t13;
t19 = (Ixx3.*t11)./2.0;
t20 = (Iyy3.*t11)./2.0;
t21 = (a2.*a3.*m3.*t9)./2.0;
t22 = (a2.*a3.*m3.*t9)./4.0;
t25 = (m3.*t4.*t11)./8.0;
t24 = -t19;
t26 = t12+t20+t22+t24+t25;
t29 = t14+t16+t18+t20+t21+t23+t24+t25;
t27 = dq1.*t26;
t30 = dq1.*t29;
t28 = -t27;
t31 = -t30;
C_mat = reshape([dq3.*t26+dq2.*t29,t31,t28,t31,(a2.*a3.*dq3.*m3.*t2)./2.0,t17,t28,t17,t17],[3,3]);
end
