function J_dot = get_J_dot(q1,q2,q3,dq1,dq2,dq3,a2,a3)
%get_J_dot
%    J_dot = get_J_dot(Q1,Q2,Q3,DQ1,DQ2,DQ3,A2,A3)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    07-Dec-2025 03:05:10

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = a2.*t2.*t3;
t9 = a2.*t2.*t6;
t10 = a2.*t3.*t5;
t11 = a2.*t5.*t6;
t12 = (a3.*t3.*t7)./2.0;
t13 = (a3.*t4.*t6)./2.0;
t14 = (a3.*t2.*t3.*t4)./2.0;
t17 = (a3.*t3.*t4.*t5)./2.0;
t18 = (a3.*t2.*t6.*t7)./2.0;
t21 = (a3.*t5.*t6.*t7)./2.0;
t15 = t2.*t12;
t16 = t2.*t13;
t19 = t5.*t12;
t20 = t5.*t13;
t22 = -t18;
t23 = -t21;
t24 = t12+t13;
t25 = dq3.*t24;
t27 = t19+t20;
t28 = t15+t16;
t29 = t17+t23;
t30 = t14+t22;
t26 = -t25;
t31 = dq3.*t30;
t32 = dq3.*t29;
t35 = t9+t28;
t36 = t11+t27;
t37 = t8+t30;
t38 = t10+t29;
t33 = -t31;
t34 = -t32;
J_dot = reshape([dq3.*t27-dq1.*t37+dq2.*t36,-dq3.*t28-dq2.*t35-dq1.*t38,0.0,t33+dq1.*t36-dq2.*t37,t34-dq1.*t35-dq2.*t38,t26-dq2.*(t24+a2.*t6),t33+dq1.*t27-dq2.*t30,t34-dq1.*t28-dq2.*t29,t26-dq2.*t24],[3,3]);
end
