function J_end_effector = get_Jacobian(q1,q2,q3,a2,a3)
%get_Jacobian
%    J_end_effector = get_Jacobian(Q1,Q2,Q3,A2,A3)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    07-Dec-2025 02:38:17

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = -t2;
t9 = (a3.*t3.*t4)./2.0;
t10 = (a3.*t6.*t7)./2.0;
t12 = (a3.*t2.*t3.*t7)./2.0;
t13 = (a3.*t2.*t4.*t6)./2.0;
t14 = (a3.*t3.*t5.*t7)./2.0;
t15 = (a3.*t4.*t5.*t6)./2.0;
t11 = -t10;
t16 = -t12;
t17 = -t13;
t18 = -t14;
t19 = -t15;
J_end_effector = reshape([t5.*t10-a2.*t3.*t5-(a3.*t3.*t4.*t5)./2.0,t2.*t9+a2.*t2.*t3-(a3.*t2.*t6.*t7)./2.0,0.0,0.0,0.0,1.0,t16+t17+a2.*t6.*t8,t18+t19-a2.*t5.*t6,t9+t11+a2.*t3,t5,t8,0.0,t16+t17,t18+t19,t9+t11,t5,t8,0.0],[6,3]);
end
