function B = get_B_matrix(q1,q2,q3,m1,m2,m3,a2,a3,Ixx1,Iyy1,Izz1,Ixx2,Iyy2,Izz2,Ixx3,Iyy3,Izz3)
%get_B_matrix
%    B = get_B_matrix(Q1,Q2,Q3,M1,M2,M3,A2,A3,Ixx1,Iyy1,Izz1,Ixx2,Iyy2,Izz2,Ixx3,Iyy3,Izz3)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    07-Dec-2025 02:38:17

t2 = cos(q3);
t3 = a2.^2;
t4 = a3.^2;
t5 = q2.*2.0;
t6 = q3.*2.0;
t7 = cos(t5);
t8 = t5+t6;
t10 = (m3.*t4)./4.0;
t11 = (a2.*a3.*m3.*t2)./2.0;
t9 = cos(t8);
t12 = Izz3+t10+t11;
B = reshape([Ixx2./2.0+Ixx3./2.0+Iyy1+Iyy2./2.0+Iyy3./2.0+t11-(Ixx2.*t7)./2.0-(Ixx3.*t9)./2.0+(Iyy2.*t7)./2.0+(Iyy3.*t9)./2.0+(m2.*t3)./8.0+(m3.*t3)./2.0+(m3.*t4)./8.0+(m2.*t3.*t7)./8.0+(m3.*t3.*t7)./2.0+(m3.*t4.*t9)./8.0+(a2.*a3.*m3.*cos(q3+t5))./2.0,0.0,0.0,0.0,Izz2+Izz3+t10+(m2.*t3)./4.0+m3.*t3+a2.*a3.*m3.*t2,t12,0.0,t12,Izz3+t10],[3,3]);
end
